### ISSUE TITLE
Update not work

### ISSUE THREAD

**Issue by pedrostefanogv** [netvolt/LinuxRMM-Script#11]
Ao executar o comando update não esta atualizando o agent 

root@zorin:/home/pedro/Downloads# ./rmmagent-linux.sh update
tar (child): /tmp/golang.tar.gz: Função open falhou: Arquivo ou diretório inexistente
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: não foi possível remover '/tmp/golang.tar.gz': Arquivo ou diretório inexistente
Golang Install Done !
Agent Compile begin
--2023-05-22 19:00:02--  https://github.com/amidaware/rmmagent/archive/refs/heads/master.zip
Resolvendo github.com (github.com)... 20.201.28.151
Conectando-se a github.com (github.com)|20.201.28.151|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 302 Found
Localização: https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master [redirecionando]
--2023-05-22 19:00:02--  https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master
Resolvendo codeload.github.com (codeload.github.com)... 20.201.28.149
Conectando-se a codeload.github.com (codeload.github.com)|20.201.28.149|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: não especificada [application/zip]
Salvando em: “/tmp/rmmagent.zip”

/tmp/rmmagent.zip       [ <=>                ]  90,28K  --.-KB/s    em 0,07s   

2023-05-22 19:00:03 (1,31 MB/s) - “/tmp/rmmagent.zip” salvo [92443]

Archive:  /tmp/rmmagent.zip
7ea714fc0408677237dd9201403582818dc363a7
   creating: /tmp/rmmagent-master/
   creating: /tmp/rmmagent-master/.github/
   creating: /tmp/rmmagent-master/.github/workflows/
  inflating: /tmp/rmmagent-master/.github/workflows/ci.yml  
  inflating: /tmp/rmmagent-master/.gitignore  
   creating: /tmp/rmmagent-master/.vscode/
  inflating: /tmp/rmmagent-master/.vscode/settings.json  
  inflating: /tmp/rmmagent-master/LICENSE.md  
  inflating: /tmp/rmmagent-master/README.md  
   creating: /tmp/rmmagent-master/agent/
  inflating: /tmp/rmmagent-master/agent/agent.go  
  inflating: /tmp/rmmagent-master/agent/agent_unix.go  
  inflating: /tmp/rmmagent-master/agent/agent_windows.go  
  inflating: /tmp/rmmagent-master/agent/checkin.go  
  inflating: /tmp/rmmagent-master/agent/checks.go  
  inflating: /tmp/rmmagent-master/agent/choco_windows.go  
  inflating: /tmp/rmmagent-master/agent/eventlog_windows.go  
  inflating: /tmp/rmmagent-master/agent/install.go  
  inflating: /tmp/rmmagent-master/agent/install_unix.go  
  inflating: /tmp/rmmagent-master/agent/install_windows.go  
  inflating: /tmp/rmmagent-master/agent/patches_windows.go  
  inflating: /tmp/rmmagent-master/agent/process.go  
  inflating: /tmp/rmmagent-master/agent/rpc.go  
  inflating: /tmp/rmmagent-master/agent/services_windows.go  
  inflating: /tmp/rmmagent-master/agent/software_windows_386.go  
  inflating: /tmp/rmmagent-master/agent/software_windows_amd64.go  
  inflating: /tmp/rmmagent-master/agent/svc.go  
  inflating: /tmp/rmmagent-master/agent/syscall_windows.go  
  inflating: /tmp/rmmagent-master/agent/tasks_windows.go  
  inflating: /tmp/rmmagent-master/agent/utils.go  
  inflating: /tmp/rmmagent-master/agent/wmi_windows.go  
  inflating: /tmp/rmmagent-master/agent/wua_windows.go  
   creating: /tmp/rmmagent-master/build/
  inflating: /tmp/rmmagent-master/build/rmm.exe.manifest  
  inflating: /tmp/rmmagent-master/build/setup.iss  
  inflating: /tmp/rmmagent-master/go.mod  
  inflating: /tmp/rmmagent-master/go.sum  
  inflating: /tmp/rmmagent-master/main.go  
   creating: /tmp/rmmagent-master/shared/
  inflating: /tmp/rmmagent-master/shared/types.go  
  inflating: /tmp/rmmagent-master/versioninfo.json  
cp: não foi possível obter estado de '/tmp/temp_rmmagent': Arquivo ou diretório inexistente
rm: não foi possível remover '/tmp/temp_rmmagent': Arquivo ou diretório inexistente
Tactical Agent Update is done

**Comment by netvolt** [comment]
Parece erro de permissão ao folder. Verifique se os Apps necessários já estão instalados, se necessário remova-os para refazer tudo do zero ok.
