### ISSUE TITLE
Is this also supposed to populate TRMM dashboard with basic info about server?

### ISSUE THREAD

**Issue by SysEngDan** [netvolt/LinuxRMM-Script#14]
First, thank you kindly for this.

I've installed this onto a CentOS 7 server and didn't experience any installation issues. Some notes about this server:

- SELinux is disabled
- Firewalld is disabled
- Server is on same LAN as the TRMM server
- No issues with disk space, RAM, or CPU

Two problems:
1. Agent is not communicating and TRMM is showing as offline, even after reboots of agent server and verifying that the tactical agent service is running with `systemctl status tacticalagent`
2. Basic information about the server is not populated in the TRMM dashboard, which may be related to the agent showing as offline

Note: The agent appeared in the TRMM dashboard immediately following the successful installation of the agent. But, since that initial appearance, no information has been received by TRMM. I was able to "Remote Control" the server once, but since rebooting, I cannot any longer.

**Comment by netvolt** [comment]
Hello Daniel, hope you are well.
Try checking if mesh service is running and If you can connect to the mesh page and control your linux device loggin/using it, before go check tactical. Tactical fills the device webpage with information received by mesh agent running. Sometimes it does not run (or install) properly or with necessary acess. Check the installation script, and double check all services installed, if they are running/active. 
As there is no code signed agent for this deployment, if you have any kind of antivirus, it might block the mesh agent services, due false positive detection.
Regards
