### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by billettg** [netvolt/LinuxRMM-Script#15]
Hi there, many thanks for the script, is there a macOS version or is the script easily adaptable? Any other known scripts that support macOS?

**Comment by netvolt** [comment]
Hello, check a fork made of one of our followers: 
https://github.com/kylefmohr/MacOSRMM-Script
Regards

**Comment by billettg** [comment]
> Hello, check a fork made of one of our followers: https://github.com/kylefmohr/MacOSRMM-Script Regards

Great, just what I was looking for, thanks for your help.

**Comment by chrisborell** [comment]
Any chance @kylefmohr could update the script for the latest version?

**Comment by kylefmohr** [comment]
@chrisborell I will take a look now!

**Comment by kylefmohr** [comment]
@chrisborell done ✅

https://github.com/kylefmohr/MacOSRMM-Script/releases/tag/v2.5.0

**Comment by chrisborell** [comment]
> @chrisborell done ✅
> 
> https://github.com/kylefmohr/MacOSRMM-Script/releases/tag/v2.5.0

You are amazing!
