### ISSUE TITLE
Installation fails on certificate error

### ISSUE THREAD

**Issue by shmoeface** [netvolt/LinuxRMM-Script#29]
Debian 12 VM, amd64 build.
Tactical RMMv0.19.3

Certificate used on the machine is a Wildcard certificate for *.fqdn.com. 
Any way to fix this without specifying the specific URL in the cert? Am I able to bypass the check somehow?
```
Go is up to date (version 1.21.5).
--2024-09-11 19:10:34--  https://mesh.fdqn.com/meshagents?id=[numbers]0&meshinstall=6
Resolving mesh.fdqn.com (mesh.fqdn.com)... 35.204.150.5
Connecting to mesh.fdqn.com (mesh.fdqn.com)|35.204.150.5|:443... connected.
ERROR: The certificate of 'mesh.fdqn.com' is not trusted.
ERROR: The certificate of 'mesh.fqdn.com' doesn't have a known issuer.
The certificate's owner does not match hostname 'mesh.fqdn.com'
mkdir: cannot create directory '/opt/tacticalmesh': File exists
rm: cannot remove '/tmp/meshagent.msh': No such file or directory
Agent Compile begin
--2024-09-11 19:10:35--  https://github.com/amidaware/rmmagent/archive/refs/heads/master.zip
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master [following]
--2024-09-11 19:10:35--  https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master
Resolving codeload.github.com (codeload.github.com)... 140.82.116.9
Connecting to codeload.github.com (codeload.github.com)|140.82.116.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 91672 (90K) [application/zip]
Saving to: '/tmp/rmmagent.zip'

/tmp/rmmagent.zip         100%[=====================================>]  89.52K  --.-KB/s    in 0.09s   

2024-09-11 19:10:35 (991 KB/s) - '/tmp/rmmagent.zip' saved [91672/91672]

Archive:  /tmp/rmmagent.zip
   creating: /tmp/rmmagent-master/
   creating: /tmp/rmmagent-master/.github/
   creating: /tmp/rmmagent-master/.github/workflows/
  inflating: /tmp/rmmagent-master/.github/workflows/ci.yml  
  inflating: /tmp/rmmagent-master/.gitignore  
   creating: /tmp/rmmagent-master/.vscode/
  inflating: /tmp/rmmagent-master/.vscode/settings.json  
  inflating: /tmp/rmmagent-master/LICENSE.md  
  inflating: /tmp/rmmagent-master/README.md  
   creating: /tmp/rmmagent-master/agent/
  inflating: /tmp/rmmagent-master/agent/agent.go  
  inflating: /tmp/rmmagent-master/agent/agent_unix.go  
  inflating: /tmp/rmmagent-master/agent/agent_windows.go  
  inflating: /tmp/rmmagent-master/agent/checkin.go  
  inflating: /tmp/rmmagent-master/agent/checks.go  
  inflating: /tmp/rmmagent-master/agent/choco_windows.go  
  inflating: /tmp/rmmagent-master/agent/embed_darwin.go  
  inflating: /tmp/rmmagent-master/agent/embed_stub.go  
  inflating: /tmp/rmmagent-master/agent/eventlog_windows.go  
  inflating: /tmp/rmmagent-master/agent/install.go  
  inflating: /tmp/rmmagent-master/agent/install_unix.go  
  inflating: /tmp/rmmagent-master/agent/install_windows.go  
  inflating: /tmp/rmmagent-master/agent/patches_windows.go  
  inflating: /tmp/rmmagent-master/agent/process.go  
  inflating: /tmp/rmmagent-master/agent/rpc.go  
   creating: /tmp/rmmagent-master/agent/scripts/
  inflating: /tmp/rmmagent-master/agent/scripts/macos_fix_mesh_install.sh  
  inflating: /tmp/rmmagent-master/agent/services_windows.go  
  inflating: /tmp/rmmagent-master/agent/software_windows_386.go  
  inflating: /tmp/rmmagent-master/agent/software_windows_amd64.go  
  inflating: /tmp/rmmagent-master/agent/svc.go  
  inflating: /tmp/rmmagent-master/agent/syscall_windows.go  
  inflating: /tmp/rmmagent-master/agent/tasks_windows.go  
  inflating: /tmp/rmmagent-master/agent/utils.go  
  inflating: /tmp/rmmagent-master/agent/wmi_windows.go  
  inflating: /tmp/rmmagent-master/agent/wua_windows.go  
   creating: /tmp/rmmagent-master/build/
  inflating: /tmp/rmmagent-master/build/rmm.exe.manifest  
  inflating: /tmp/rmmagent-master/build/setup.iss  
  inflating: /tmp/rmmagent-master/go.mod  
  inflating: /tmp/rmmagent-master/go.sum  
  inflating: /tmp/rmmagent-master/main.go  
   creating: /tmp/rmmagent-master/shared/
  inflating: /tmp/rmmagent-master/shared/types.go  
  inflating: /tmp/rmmagent-master/versioninfo.json  
cp: cannot create regular file '/usr/local/bin/rmmagent': Text file busy
FATA[0000] Get "https://api.fqdn.com/api/v3/installer/": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match api.fqdn.com 
Tactical Agent Install is done```

**Comment by guilhermefr67** [comment]
Hi

In `function install_agent` on line 234, just put the `--insecure` parameter before `-api`.
here is an example

```
function install_agent() {
        cp /tmp/temp_rmmagent /usr/local/bin/rmmagent
         /tmp/temp_rmmagent -m install **--insecure** -api $rmm_url -client-id $rmm_client_id -site-id $rmm_site_id -agen    t-type $rmm_agent_type -auth $rmm_auth
         rm /tmp/temp_rmmagent
```
Here it worked correctly

**Comment by guilhermefr67** [comment]
> Debian 12 VM, amd64 build. Tactical RMMv0.19.3
> 
> Certificate used on the machine is a Wildcard certificate for *.fqdn.com. Any way to fix this without specifying the specific URL in the cert? Am I able to bypass the check somehow?
> 
> ```
> Go is up to date (version 1.21.5).
> --2024-09-11 19:10:34--  https://mesh.fdqn.com/meshagents?id=[numbers]0&meshinstall=6
> Resolving mesh.fdqn.com (mesh.fqdn.com)... 35.204.150.5
> Connecting to mesh.fdqn.com (mesh.fdqn.com)|35.204.150.5|:443... connected.
> ERROR: The certificate of 'mesh.fdqn.com' is not trusted.
> ERROR: The certificate of 'mesh.fqdn.com' doesn't have a known issuer.
> The certificate's owner does not match hostname 'mesh.fqdn.com'
> mkdir: cannot create directory '/opt/tacticalmesh': File exists
> rm: cannot remove '/tmp/meshagent.msh': No such file or directory
> Agent Compile begin
> --2024-09-11 19:10:35--  https://github.com/amidaware/rmmagent/archive/refs/heads/master.zip
> Resolving github.com (github.com)... 140.82.116.3
> Connecting to github.com (github.com)|140.82.116.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master [following]
> --2024-09-11 19:10:35--  https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master
> Resolving codeload.github.com (codeload.github.com)... 140.82.116.9
> Connecting to codeload.github.com (codeload.github.com)|140.82.116.9|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 91672 (90K) [application/zip]
> Saving to: '/tmp/rmmagent.zip'
> 
> /tmp/rmmagent.zip         100%[=====================================>]  89.52K  --.-KB/s    in 0.09s   
> 
> 2024-09-11 19:10:35 (991 KB/s) - '/tmp/rmmagent.zip' saved [91672/91672]
> 
> Archive:  /tmp/rmmagent.zip
>    creating: /tmp/rmmagent-master/
>    creating: /tmp/rmmagent-master/.github/
>    creating: /tmp/rmmagent-master/.github/workflows/
>   inflating: /tmp/rmmagent-master/.github/workflows/ci.yml  
>   inflating: /tmp/rmmagent-master/.gitignore  
>    creating: /tmp/rmmagent-master/.vscode/
>   inflating: /tmp/rmmagent-master/.vscode/settings.json  
>   inflating: /tmp/rmmagent-master/LICENSE.md  
>   inflating: /tmp/rmmagent-master/README.md  
>    creating: /tmp/rmmagent-master/agent/
>   inflating: /tmp/rmmagent-master/agent/agent.go  
>   inflating: /tmp/rmmagent-master/agent/agent_unix.go  
>   inflating: /tmp/rmmagent-master/agent/agent_windows.go  
>   inflating: /tmp/rmmagent-master/agent/checkin.go  
>   inflating: /tmp/rmmagent-master/agent/checks.go  
>   inflating: /tmp/rmmagent-master/agent/choco_windows.go  
>   inflating: /tmp/rmmagent-master/agent/embed_darwin.go  
>   inflating: /tmp/rmmagent-master/agent/embed_stub.go  
>   inflating: /tmp/rmmagent-master/agent/eventlog_windows.go  
>   inflating: /tmp/rmmagent-master/agent/install.go  
>   inflating: /tmp/rmmagent-master/agent/install_unix.go  
>   inflating: /tmp/rmmagent-master/agent/install_windows.go  
>   inflating: /tmp/rmmagent-master/agent/patches_windows.go  
>   inflating: /tmp/rmmagent-master/agent/process.go  
>   inflating: /tmp/rmmagent-master/agent/rpc.go  
>    creating: /tmp/rmmagent-master/agent/scripts/
>   inflating: /tmp/rmmagent-master/agent/scripts/macos_fix_mesh_install.sh  
>   inflating: /tmp/rmmagent-master/agent/services_windows.go  
>   inflating: /tmp/rmmagent-master/agent/software_windows_386.go  
>   inflating: /tmp/rmmagent-master/agent/software_windows_amd64.go  
>   inflating: /tmp/rmmagent-master/agent/svc.go  
>   inflating: /tmp/rmmagent-master/agent/syscall_windows.go  
>   inflating: /tmp/rmmagent-master/agent/tasks_windows.go  
>   inflating: /tmp/rmmagent-master/agent/utils.go  
>   inflating: /tmp/rmmagent-master/agent/wmi_windows.go  
>   inflating: /tmp/rmmagent-master/agent/wua_windows.go  
>    creating: /tmp/rmmagent-master/build/
>   inflating: /tmp/rmmagent-master/build/rmm.exe.manifest  
>   inflating: /tmp/rmmagent-master/build/setup.iss  
>   inflating: /tmp/rmmagent-master/go.mod  
>   inflating: /tmp/rmmagent-master/go.sum  
>   inflating: /tmp/rmmagent-master/main.go  
>    creating: /tmp/rmmagent-master/shared/
>   inflating: /tmp/rmmagent-master/shared/types.go  
>   inflating: /tmp/rmmagent-master/versioninfo.json  
> cp: cannot create regular file '/usr/local/bin/rmmagent': Text file busy
> FATA[0000] Get "https://api.fqdn.com/api/v3/installer/": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match api.fqdn.com 
> Tactical Agent Install is done```
> ```

Hi

In `function install_agent` on line 234, just put the `--insecure` parameter before `-api`.
here is an example

```
function install_agent() {
        cp /tmp/temp_rmmagent /usr/local/bin/rmmagent
         /tmp/temp_rmmagent -m install **--insecure** -api $rmm_url -client-id $rmm_client_id -site-id $rmm_site_id -agen    t-type $rmm_agent_type -auth $rmm_auth
         rm /tmp/temp_rmmagent
```

Here it worked correctly

**Comment by shmoeface** [comment]
> > Debian 12 VM, amd64 build. Tactical RMMv0.19.3
> > Certificate used on the machine is a Wildcard certificate for *.fqdn.com. Any way to fix this without specifying the specific URL in the cert? Am I able to bypass the check somehow?
> > ```
> > Go is up to date (version 1.21.5).
> > --2024-09-11 19:10:34--  https://mesh.fdqn.com/meshagents?id=[numbers]0&meshinstall=6
> > Resolving mesh.fdqn.com (mesh.fqdn.com)... 35.204.150.5
> > Connecting to mesh.fdqn.com (mesh.fdqn.com)|35.204.150.5|:443... connected.
> > ERROR: The certificate of 'mesh.fdqn.com' is not trusted.
> > ERROR: The certificate of 'mesh.fqdn.com' doesn't have a known issuer.
> > The certificate's owner does not match hostname 'mesh.fqdn.com'
> > mkdir: cannot create directory '/opt/tacticalmesh': File exists
> > rm: cannot remove '/tmp/meshagent.msh': No such file or directory
> > Agent Compile begin
> > --2024-09-11 19:10:35--  https://github.com/amidaware/rmmagent/archive/refs/heads/master.zip
> > Resolving github.com (github.com)... 140.82.116.3
> > Connecting to github.com (github.com)|140.82.116.3|:443... connected.
> > HTTP request sent, awaiting response... 302 Found
> > Location: https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master [following]
> > --2024-09-11 19:10:35--  https://codeload.github.com/amidaware/rmmagent/zip/refs/heads/master
> > Resolving codeload.github.com (codeload.github.com)... 140.82.116.9
> > Connecting to codeload.github.com (codeload.github.com)|140.82.116.9|:443... connected.
> > HTTP request sent, awaiting response... 200 OK
> > Length: 91672 (90K) [application/zip]
> > Saving to: '/tmp/rmmagent.zip'
> > 
> > /tmp/rmmagent.zip         100%[=====================================>]  89.52K  --.-KB/s    in 0.09s   
> > 
> > 2024-09-11 19:10:35 (991 KB/s) - '/tmp/rmmagent.zip' saved [91672/91672]
> > 
> > Archive:  /tmp/rmmagent.zip
> >    creating: /tmp/rmmagent-master/
> >    creating: /tmp/rmmagent-master/.github/
> >    creating: /tmp/rmmagent-master/.github/workflows/
> >   inflating: /tmp/rmmagent-master/.github/workflows/ci.yml  
> >   inflating: /tmp/rmmagent-master/.gitignore  
> >    creating: /tmp/rmmagent-master/.vscode/
> >   inflating: /tmp/rmmagent-master/.vscode/settings.json  
> >   inflating: /tmp/rmmagent-master/LICENSE.md  
> >   inflating: /tmp/rmmagent-master/README.md  
> >    creating: /tmp/rmmagent-master/agent/
> >   inflating: /tmp/rmmagent-master/agent/agent.go  
> >   inflating: /tmp/rmmagent-master/agent/agent_unix.go  
> >   inflating: /tmp/rmmagent-master/agent/agent_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/checkin.go  
> >   inflating: /tmp/rmmagent-master/agent/checks.go  
> >   inflating: /tmp/rmmagent-master/agent/choco_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/embed_darwin.go  
> >   inflating: /tmp/rmmagent-master/agent/embed_stub.go  
> >   inflating: /tmp/rmmagent-master/agent/eventlog_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/install.go  
> >   inflating: /tmp/rmmagent-master/agent/install_unix.go  
> >   inflating: /tmp/rmmagent-master/agent/install_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/patches_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/process.go  
> >   inflating: /tmp/rmmagent-master/agent/rpc.go  
> >    creating: /tmp/rmmagent-master/agent/scripts/
> >   inflating: /tmp/rmmagent-master/agent/scripts/macos_fix_mesh_install.sh  
> >   inflating: /tmp/rmmagent-master/agent/services_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/software_windows_386.go  
> >   inflating: /tmp/rmmagent-master/agent/software_windows_amd64.go  
> >   inflating: /tmp/rmmagent-master/agent/svc.go  
> >   inflating: /tmp/rmmagent-master/agent/syscall_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/tasks_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/utils.go  
> >   inflating: /tmp/rmmagent-master/agent/wmi_windows.go  
> >   inflating: /tmp/rmmagent-master/agent/wua_windows.go  
> >    creating: /tmp/rmmagent-master/build/
> >   inflating: /tmp/rmmagent-master/build/rmm.exe.manifest  
> >   inflating: /tmp/rmmagent-master/build/setup.iss  
> >   inflating: /tmp/rmmagent-master/go.mod  
> >   inflating: /tmp/rmmagent-master/go.sum  
> >   inflating: /tmp/rmmagent-master/main.go  
> >    creating: /tmp/rmmagent-master/shared/
> >   inflating: /tmp/rmmagent-master/shared/types.go  
> >   inflating: /tmp/rmmagent-master/versioninfo.json  
> > cp: cannot create regular file '/usr/local/bin/rmmagent': Text file busy
> > FATA[0000] Get "https://api.fqdn.com/api/v3/installer/": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match api.fqdn.com 
> > Tactical Agent Install is done```
> > ```
> 
> Hi
> 
> In `function install_agent` on line 234, just put the `--insecure` parameter before `-api`. here is an example
> 
> ```
> function install_agent() {
>         cp /tmp/temp_rmmagent /usr/local/bin/rmmagent
>          /tmp/temp_rmmagent -m install **--insecure** -api $rmm_url -client-id $rmm_client_id -site-id $rmm_site_id -agen    t-type $rmm_agent_type -auth $rmm_auth
>          rm /tmp/temp_rmmagent
> ```
> 
> Here it worked correctly

That worked perfectly, thank you.
