### ISSUE TITLE
Unzip not found (installed tho)

### ISSUE THREAD

**Issue by nopam-og** [netvolt/LinuxRMM-Script#4]
Hi!
For some reason when running your script, I get the error unzip could not be found.
Though I checked, it is installed, and in the $PATH variable.
![image](https://user-images.githubusercontent.com/56748179/208088891-fd489f87-d9f6-428d-bd62-07d34a34ecd3.png)

**Comment by nopam-og** [comment]
Here you can see, unzip works perfectly.
![image](https://user-images.githubusercontent.com/56748179/208089100-23265b60-bf97-4d0f-9ae9-5d6fa36b978f.png)

Also when I remove the -v tag from the top of the script, it runs unzip, and shows me the output.

**Comment by netvolt** [comment]
Updated code for a new kind of check for unzip. Please check and advise. We checked in CentOS and Debian flavors.

**Comment by nopam-og** [comment]
> Updated code for a new kind of check for unzip. Please check and advise. We checked in CentOS and Debian flavors.

Cool!
Now I get a different output:
![image](https://user-images.githubusercontent.com/56748179/208487081-b731cbe3-0c49-4adc-b112-60e60b198648.png)

**Comment by nopam-og** [comment]
> 

Is there supposed to be a ZIP in the directory of the script?

**Comment by netvolt** [comment]
> > 
> 
> Is there supposed to be a ZIP in the directory of the script?

No, it just need to be installed as root. Are you running script as root? What is your flavor and version?

**Comment by nopam-og** [comment]
> > > 
> > 
> > 
> > Is there supposed to be a ZIP in the directory of the script?
> 
> No, it just need to be installed as root. Are you running script as root? What is your flavor and version?

Okay, the script is in /root and I'm running it with the root user:.
I'm currently on Debian 11.

**Comment by netvolt** [comment]
can you post the script call code just like you are running it? (replace important IDs with X's)

**Comment by nopam-og** [comment]
sudo sh ./rmmagent-linux.sh install amd64 "https://xxxx/meshagents?id=xxxxxxxxxxxxxxxxxx&installflags=0&meshinstall=6" "https://api.xxxxx.com" 1 1 "xxxxxxxxxxxxxxxx" server

**Comment by netvolt** [comment]
Try this format of installation

`sudo ./rmmagent-linux.sh install 'amd64' 'https://mesh.xxxxx.com/meshagents?id=xxxxxxxxxxxxxxxxxx&installflags=0&meshinstall=6' 'https://api.xxxxx.com' '1' '1' 'XXXXXXXXXXXXXX' 'server'
`
Usually calling a bash script is not necessary to use "sh" before the "./script.sh", that might be the problem in your case.

**Comment by nopam-og** [comment]
> Try this format of installation
> 
> `sudo ./rmmagent-linux.sh install 'amd64' 'https://mesh.xxxxx.com/meshagents?id=xxxxxxxxxxxxxxxxxx&installflags=0&meshinstall=6' 'https://api.xxxxx.com' '1' '1' 'XXXXXXXXXXXXXX' 'server' ` Usually calling a bash script is not necessary to use "sh" before the "./script.sh", that might be the problem in your case.

Still getting errors:
![image](https://user-images.githubusercontent.com/56748179/208532167-78727e09-dd97-4df8-a0ea-b45f2a2cb127.png)

**Comment by nopam-og** [comment]
Fixed it by performing: `chmod +x rmmagent-linux.sh`
Much appreciation for your support! <3
